### ISSUE TITLE
Including jqr sources

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#1]
For eventual CRAN release, we'll need to include the jqr sources.  I've held off doing that for now partly because they're big *and require some careful .gitignore editing) and partly so that the distribution requirements/obligations are met.  

* I think we need to list the jqr authors in the DESCRIPTION field - there's some advice on this *somewhere* in R-exts.
* Decide whether to keep the versioned src/jq-<version> directory.  If so, try to DRY the code up (src/Makevars and bootstrap.R)
* Make sure we never commit any generated jq files
* Document the weird munging of the obsolete m4 macros

**Comment by sckott** [comment]
for listing authors, perhaps like in git2r https://github.com/ropensci/git2r/blob/master/DESCRIPTION#L13 and the AUTHORS file in `/inst` https://github.com/ropensci/git2r/blob/master/inst/AUTHORS

**Comment by richfitz** [comment]
Good idea - we can automatically include the AUTHORS file from jq during bootstrap (https://github.com/stedolan/jq/blob/master/AUTHORS)
