### ISSUE TITLE
chmod not found on windows

### ISSUE THREAD

**Issue by sckott** [ropensci/jqr#13]
screenshot form my windows machine 

![](http://f.cl.ly/items/3h0w2e1q20391a3a3E2C/Screen%20Shot%202015-06-08%20at%203.49.11%20PM.png)

is there an easy way to fix this?

**Comment by justa9** [comment]
Yes. You may install gnuwin32 coreutils which include a chmod.exe. 
http://gnuwin32.sourceforge.net/packages/coreutils.htm

I successfully managed to build the development version of jqr on Windows XP (!) by doing exactly that. All tests I ran from the mainpage produced the expected results.


```
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (jqr)
> library("jqr")
> str <- '[{
+     "foo": 1,
+     "bar": 2
+   },
+   {
+     "foo": 3,
+     "bar": 4
+   },
+   {
+     "foo": 5,
+     "bar": 6
+ }]'
> jq_(str, ".[]")
[1] "{\"foo\":1,\"bar\":2}" "{\"foo\":3,\"bar\":4}" "{\"foo\":5,\"bar\":6}"
> jq_(str, "[.[] | {name: .foo} | keys]")
[1] "[[\"name\"],[\"name\"],[\"name\"]]"
> x <- '[{"message": "hello", "name": "jenn"}, {"message": "world", "name": "b$
> x %>% index() %>% jq
{"message":"hello","name":"jenn"} {"message":"world","name":"beth"}
> '[8,3,null,6]' %>% sortj %>% jq
[null,3,6,8]
> '[1,2,3,4]' %>% reverse %>% jq
[4,3,2,1]
> '[1,2,3,4]' %>%  reverse %>% peek
<jq query>
  query:  reverse>
> '["a","b,c,d","e"]' %>% join %>% jq
"a, b,c,d, e"
> '["a","b,c,d","e"]' %>% join(`;`) %>% jq
"a; b,c,d; e"
> '["fo", "foo", "barfoo", "foobar", "afoo"]' %>% index() %>% ltrimstr(foo) %>$
"fo" "" "barfoo" "bar" "afoo"
```


Another thing: Would you find it useful if jqr was extended so that it can act as a wrapper to an independently-build binary, via an option such as "use.external.binary=TRUE" ?

**Comment by richfitz** [comment]
jqr is not using the jq program, but libjq which I don't think is installed by default?

**Comment by sckott** [comment]
@justa9 Great, thanks for trying jqr!

I'm not sure what the best approach is here, so I'm just asking questions.  

> You may install gnuwin32 coreutils which include a chmod.exe. http://gnuwin32.sourceforge.net/packages/coreutils.htm

@richfitz for the above, this would require user to do that manually, right? I think we want a solution that doesn't require an extra user step ideally

**Comment by richfitz** [comment]
Fixed on branch, waiting for merge.

**Comment by sckott** [comment]
i assume this is done, reopen if not @richfitz
