### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#19]
Once the DSL exists, need a vignette.

Might be worth having material covering both the DSL and direct interface.

**Comment by sckott** [comment]
- [ ] low level vignette
- [ ] DSL vignette

**Comment by sckott** [comment]
started DSL vignette, not done yet

**Comment by smbache** [comment]
I think there is a pretty nice/seamless integration between low-level and dsl, with the new generic setup; thinking perhaps a single vignette will suffice?

**Comment by sckott** [comment]
Yeah, you're probably right.

**Comment by sckott** [comment]
vignette updated, focused on both high and low level, though mostly DSL

**Comment by smbache** [comment]
Will have a look

**Comment by sckott** [comment]
@richfitz @smbache Okay with the vignette?  If so, we're ready to go. Rich, you are listed as maintainer. can you submit? or we can switch maintainers and I submit

**Comment by richfitz** [comment]
Switch maintainer perhaps?

**Comment by sckott** [comment]
Okay, will do

**Comment by smbache** [comment]
1) would it be useful with a short summary initially of jq is, for those unfamiliar? Just as to get an idea without having to visit the jq site?

2) no need for explicit name dropping ;-)

**Comment by sckott** [comment]
> would it be useful with a short summary initially of jq is, for those unfamiliar? Just as to get an idea without having to visit the jq site?

More than this ? https://github.com/ropensci/jqr/blob/master/vignettes/jqr_vignette.Rmd#introduction-to-jqr

> no need for explicit name dropping ;-)

what do you mean?

**Comment by smbache** [comment]
I guess it's fine, but I think that if you have no clue what it is, and want to know just a bit more than "json processor", you'll probably visit the jq page first... Which may be ok.

I mean the part where my name is explicitly "dropped" related to the pipe hack ;) now that I'm listed in the description that's more than enough, heh..

**Comment by sckott** [comment]
Right, will add more jq info, And will remove name drop :)

**Comment by smbache** [comment]
:)

**Comment by sckott** [comment]
i'll close this unless any other thoughts...
