### ISSUE TITLE
"." filter and pretty printing.

### ISSUE THREAD

**Issue by smbache** [ropensci/jqr#27]
From the manual:

"Since jq by default pretty-prints all output, this trivial program can be a useful way of formatting JSON output from, say, curl."

for input `{"foo":[{"bar":"baz"}]}` `jq`  with the basic `.` filter produces: 

```
{
  "foo": [
    {
      "bar": "baz"
    }
  ]
}

```

`jqr` produces:

```R
> '{"foo":[{"bar":"baz"}]}' %>% dot() %>% pretty
{"foo":[{"bar":"baz"}]}

> '{"foo":[{"bar":"baz"}]}' %>% jq(".") 
{"foo":[{"bar":"baz"}]} 
```

Is this a deliberate choice? I can see the usefulness og the default "prettying"...

**Comment by sckott** [comment]
Good point.  I don't think we've thought about this, at least I haven't. 

I'll have a think about it. It does probably make sense to pretty print with newlines

**Comment by smbache** [comment]
Mostly for consistency with the standard `jq` behavior. I think this is what people would expect as it's almost the first lesson in the docs for `jq` :)

**Comment by sckott** [comment]
okay, pushed a change, should behave just like `jq` now, via `jqr::combine()`

**Comment by sckott** [comment]
i think this is sorted now

**Comment by smbache** [comment]
Yes! It's good!
