### ISSUE TITLE
Hex sticker?

### ISSUE THREAD

**Issue by smbache** [ropensci/jqr#29]
If so, let's see some ideas :)

**Comment by karthik** [comment]
Lol!

**Comment by richfitz** [comment]
:+1:

**Comment by kylehamilton** [comment]
Here's a package that we used for making the hex sticker for [mchtoolbox](https://github.com/ropenscilabs/mchtoolbox)
https://github.com/GuangchuangYu/hexSticker

**Comment by sckott** [comment]
thanks @kylehamilton
