### ISSUE TITLE
pretty masks base::pretty

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#32]
Giving the always tedious warning:

"The following object is masked from package:base"...

I'd rather not export a function that will clash with a base package -- can we rename?

**Comment by sckott** [comment]
`prettify` is in 3 diff. pkgs so far. maybe `prettied`

**Comment by richfitz** [comment]
`pretty_json`?, `jpretty`?

**Comment by sckott** [comment]
oooh, i know: `prettiest`

**Comment by richfitz** [comment]
Which means the person next in this situation can go for `no_really_mine_is_the_prettiest`

**Comment by richfitz** [comment]
How about `superprettyfragilisticexpialidocious`?

**Comment by smbache** [comment]
Is it needed now that pretty is default?

**Comment by sckott** [comment]
`superprettyfragilisticexpialidocious` - yes! amazing

to be real for just a bit, looking at the fxn again, not sure we need it. Okay if we drop it? If users want to do pretty printing separately, better to use `jsonlite::prettify` anyway. That's what we use internally in `print.jqson()`

**Comment by smbache** [comment]
Indeed

**Comment by richfitz** [comment]
:+1: 

![drop it](http://i.giphy.com/KQyKXywaKJD4Q.gif)
