### ISSUE TITLE
Trailing newline needed, at least on Linux

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#36]
In the print method I don't get the right number of newlines.

```
> '{"a": 7}' %>% do(.a + 1) %>% peek
<jq query>
  query:  .a + 1> # this would be new prompt here!
```

If this applies across platforms (don't have time check RN), the fix would be

```
> jqr:::print.jq_query
function (x, ...) 
{
    cat("<jq query>", sep = "\n")
    cat("  query: ", x)
}
```

The last cat call needs a "\n"; so becomes `cat(sprintf("query: %s\n", x))` (note as it is it also adds an extra space too because cat does that.

**Comment by sckott** [comment]
nice catch. - though I like the indentation if that's okay 

```r
print.jq_query <- function(x, ...) {
  cat("<jq query>", sep = "\n")
  cat(sprintf("  query: %s\n", x))
}
```

on cli with change (my prompts are `<r>`)

```r
<r> '{"a": 7}' %>% do(.a + 1) %>% peek
<jq query>
  query: .a + 1
<r>
```

**Comment by richfitz** [comment]
The indentation is great - removing that was accidental.
