### ISSUE TITLE
Eliminate additional compiler warnings

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#37]
```
jq/jv.h:41:12: warning: unused function 'jv_is_valid' [-Wunused-function]
static int jv_is_valid(jv x) { return jv_get_kind(x) != JV_KIND_INVALID; }
```

```
jq/jv_alloc.h:11:13: warning: unused function 'jv_mem_invalidate'
      [-Wunused-function]
static void jv_mem_invalidate(void* mem, size_t n) {
            ^
```

```
jq/execute.c:68:22: warning: unused variable 'bc' [-Wunused-variable]
    struct bytecode* bc = fpnext->bc;
                     ^
jq/execute.c:193:9: warning: unused variable 'n1' [-Wunused-variable]
    int n1 = jv_array_length(jv_copy(jq->path));
        ^
jq/execute.c:195:9: warning: unused variable 'n2' [-Wunused-variable]
    int n2 = jv_array_length(jv_copy(jq->path));
        ^
In file included from jq/execute.c:12:
```

```
lexer.c:1933:16: warning: unused function 'yy_top_state' [-Wunused-function]
    static int yy_top_state  (yyscan_t yyscanner)
               ^

```

**Comment by sckott** [comment]
@richfitz since you attached the cran release milestone, I assume you think it should be dealt with before pushing, right?

**Comment by richfitz** [comment]
Yeah, if you don't mind.  Or you could take a stab at submitting it and see what they say.  But I think CRAN tends to be pretty picky with packages that contain compiled code.

**Comment by sckott** [comment]
nah, let's get it done first

**Comment by smbache** [comment]
any news with this?

**Comment by sckott** [comment]
tried seeing how to sort out the unused fxn warnings, not sure how best to do it, if someone could point me in the right direction...

**Comment by jeroenooms** [comment]
This warning is usually harmless, I don't think it shows up in `CMD check`. But you might be able to suppress it with:

```
PKG_CFLAGS = -Wno-unused-variable -Wno-unused-function
```

**Comment by richfitz** [comment]
Sorry, I'll have a look at this soon, Scott.

I would have thought that the `-Wno*` flags would raise ire on CRAN for lack of portability?  I'd still like to remove the unused functions though.

**Comment by jeroenooms** [comment]
Unused variables or functions often appear only on certain platforms, usually because they are inside a platform specific `#ifdef` block. Therefore CRAN usually ignores them I think.

**Comment by richfitz** [comment]
Let's just see what happens on CRAN.
