### ISSUE TITLE
cran copyrights / license fix

### ISSUE THREAD

**Issue by sckott** [ropensci/jqr#41]
> Thanks, we see: 

> You have files in your package with GPLK license and copyright holders
not declared in the Authors@R fiel. Example: file src/parser.c (GPL,
copyright holder is the FSF).

> Please carefully check if your license is possible and if all copyright
holders are mentioned.

We do have a  `COPYING.jq` file and an `AUTHORS.jq` file. 

* authors: should we do what's done in git2r https://github.com/ropensci/git2r/blob/master/DESCRIPTION#L13
* copyright: likewise for copyrights? https://github.com/ropensci/git2r/blob/master/DESCRIPTION#L9
* license: We're using MIT now, might we need to switch to something else?

**Comment by richfitz** [comment]
From that parser file:

```
/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
```

Not sure what the right move is here, and heading to bed...

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
thoughts @cboettig @jeroenooms  never had to deal with copyright/license stuff, what's the right way to handle this, should we follow what's been done with `git2r` and points to copyright and authors files in `inst/` 

Not sure what license to use either

**Comment by cboettig** [comment]
@jeroenooms would know best, but here's my take:  I guess they are suggesting that the authors of the included code be added as contributors `[ctb]` in the DESCRIPTION with a comment explaining their role (see https://github.com/rstudio/rmarkdown/blob/master/DESCRIPTION), and the DESCRIPTION should declare a compatible license.  For instance, `rmarkdown` declares GPL-3 as the overall package license, and includes a `inst/NOTICE` file that lists the licenses of all the bits and pieces: https://github.com/rstudio/rmarkdown/blob/master/inst/NOTICE , (which include MIT, GPL, etc, which are all GPL compatible, but not all MIT compatible -- looks like we distribute GPL'd code here so we are thus infected and must also use GPL, if I understand correctly).

**Comment by sckott** [comment]
this is what J said in slack 

> Also maybe use `person(“Free Software Foundation", role = c("aut","cph"), comment = “Parser code")`. For Brotli I did this: https://github.com/jeroenooms/brotli/blob/master/DESCRIPTION.  Maybe link this file in the description? https://github.com/ropensci/jqr/blob/master/src/jq/AUTHORS

**Comment by sckott** [comment]
thanks @cboettig

**Comment by sckott** [comment]
@cboettig hmm, I think we can do MIT b/c `jq` uses MIT, and they include bison in the code base, see the special exception above listed by rich.  So I think we can do MIT as well
