### ISSUE TITLE
Prepare bugfix release

### ISSUE THREAD

**Issue by jeroenooms** [ropensci/jqr#49]
I fixed [the problem](https://github.com/ropensci/jqr/commit/01a6dce2e3f04dc1fea61730cc79ab77ece76035) which caused the crashes under ASAN/valgrind on CRAN.

**Comment by sckott** [comment]
nice, I assume #43 isn't ready yet?  if so, we can include both issues

**Comment by jeroenooms** [comment]
I don't think so, haven't heard back from @else. Let's do a bugfix release with this fix, that will make cran happier.

**Comment by sckott** [comment]
okay, sounds good

**Comment by sckott** [comment]
assigned milestone `v0.2.4` - anything else to include?

**Comment by jeroenooms** [comment]
No just this patch.
