### ISSUE TITLE
jq should be able to take file paths or a URL as an argument

### ISSUE THREAD

**Issue by cboettig** [ropensci/jqr#55]
From a purely user-interface / convenience perspective, it would be nice for jq function to be able to take a file path or URL as an argument, just so that the interface is consistent with the interface of things like fromJSON, jsonld_* fns, etc.

**Comment by sckott** [comment]
thanks @cboettig 

agree this would be good - will look into it

**Comment by sckott** [comment]
@cboettig  playing around on `remotes::install_github("ropensci/jqr@input")` - can you try now with file paths and urls? see, e.g, https://github.com/ropensci/jqr/blob/input/R/jqr.R#L30-L37

**Comment by jeroen** [comment]
Ah sorry @sckott I didn't realize you were also working on this. I just pushed streaming support to master.

**Comment by sckott** [comment]
@jeroen no worries, my attempt was just trying to handle files and urls, i'm sure what you did is better

**Comment by jeroen** [comment]
Yes I rewrote the internals on my flight to YVR. You can now do incremental parsing. See `?jqr_new.

**Comment by sckott** [comment]
sorted now
