### ISSUE TITLE
warning with r-devel

### ISSUE THREAD

**Issue by sckott** [ropensci/jqr#58]
@jeroen was about to submit to CRAN - but this warning arises with R-devel on winbuilder and I imagine they'd reject it until fixed

```r
Found the following significant warnings:
  jq/builtin.c:1446:1: warning: string length '14820' is greater than the length '4095' ISO C99 compilers are required to support [-Woverlength-strings]
See 'd:/RCompile/CRANguest/R-devel/jqr.Rcheck/00install.out' for details.
```

any ideas how to fix?

**Comment by sckott** [comment]
thanks

**Comment by jeroen** [comment]
I noticed debian finally has jq, so we could choose to unbundle libjq alltogether.

**Comment by sckott** [comment]
nice, you already have a PR at https://github.com/ropensci/jqr/pull/43 for this

**Comment by jeroen** [comment]
Right, so we just need to decide if we want to do this. It will make maintenance much easier. But people will need to `brew install jq` if they want to build from source.

**Comment by sckott** [comment]
hmmm, the way you set it up, it does give an error message saying to brew install though, yes?

**Comment by sckott** [comment]
seems good now, closing
