### ISSUE TITLE
jq() should be able to take `json` as an input type?

### ISSUE THREAD

**Issue by cboettig** [ropensci/jqr#62]
If you have a `json` object (i.e. from `jsonlite::toJSON`) you currently have to coerce it to a string with `as.character` before you can call `jqr::jq` on it.  Seems like `jqr` should be able to work with `json` class objects directly (i.e. do that coercion to string internally, which I think is just hacking off the class since it's really already a string)

**Comment by sckott** [comment]
true, good point.
