### ISSUE TITLE
sysreqs

### ISSUE THREAD

**Issue by maelle** [ropensci/jqr#73]
@jeroen `jqr` dependencies do not seem to be in sysreqs DB yet? Here is probably not the best place to open an issue though 🤔 

``` r
codemetar:::get_sys_links("jqr", "libjq: jq-devel (rpm) or libjq-dev (deb)")
#> character(0)
```

Created on 2018-05-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jeroen** [comment]
Yes better open an issue or pull request in sysreqdb.

**Comment by maelle** [comment]
https://github.com/r-hub/sysreqsdb/issues/43
