### ISSUE TITLE
Release 1.1.0 or note that build_object is only available if installed from GitHub

### ISSUE THREAD

**Issue by hammer** [ropensci/jqr#74]
I like the `build_object` syntax but was surprised to not find it in the `jqr` namespace. Upon further inspection I realized it's not in the currently released `1.0.0`. Any reason not to cut a `1.1.0` release? If so, it's probably worth noting in the README that `build_object` won't be found in the currently released version.

**Comment by hammer** [comment]
Hmm when I try to install from GitHub I get:

```
Error in fetch(key) : 
  lazy-load database '/home/hammer/lib/R/library/jqr/help/jqr.rdb' is corrupt
```

**Comment by sckott** [comment]
@hammer thanks for the issue. 

> when I try to install from GitHub I get

I often solve this by restarting the R session

**Comment by hammer** [comment]
> I often solve this by restarting the R session

Ha indeed I tried the "power cycle" and it did not resolve the issue; I can do more debugging if it's not a known problem.

**Comment by sckott** [comment]
ok. does `remove.packages("jqr")` then reinstall `remotes::install_github("ropensci/jqr")` work?

**Comment by sckott** [comment]
> Any reason not to cut a 1.1.0 release?

I'm looking through the issues for this milestone to see where we're at

**Comment by sckott** [comment]
submitting today
