### ISSUE TITLE
libjq was not found on Linux systems

### ISSUE THREAD

**Issue by PoGibas** [ropensci/jqr#77]
`install.packages("jqr")` returns `Configuration failed because libjq was not found` on:

- CentOS Linux 7 (3.5.1)
- Ubuntu 16.04.4 (3.5.1)

But works on macOS Mojave (3.5.2). 

It's possible to specify path using suggested method from the error message:

```
On Ubuntu 14.04 or 16.04 you can use the PPA:
  sudo add-apt-repository -y ppa:opencpu/jq
  sudo apt-get update
  sudo apt-get install libjq-dev
On other sytems try installing:
 * deb: libjq-dev (Debian, Ubuntu 16.10 and up).
 * rpm: jq-devel (Fedora, EPEL)
 * csw: libjq_dev (Solaris)
 * brew: jq (OSX)
If  is already installed set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

However this causes problems when trying to pass Travis CI

**Comment by sckott** [comment]
sounds like your use case is tyring to install jq on travis?  or both on your own machine and travis? can you share the actual error message you get

**Comment by jeroen** [comment]
Try to using the same [`.travis`](https://github.com/ropensci/jqr/blob/master/.travis.yml) configuration as this repo:

https://github.com/ropensci/jqr/blob/5d2c2f7a3688b0da8b3b99688da70b3df7385bb4/.travis.yml#L19-L24
