### ISSUE TITLE
Incorporate streaming

### ISSUE THREAD

**Issue by richfitz** [ropensci/jqr#8]
The bits that we put together in [rivr](https://github.com/vsbuffalo/rivr) should be useful here.

**Comment by sckott** [comment]
@richfitz you added `jq_iterator()` and tests - more to add? or should we close

**Comment by sckott** [comment]
@richfitz hmm, you added this to the CRAN release milestone. I thought we were dropping `rivr` things for now, and bringing back later possibly?  I made man file for `jq_iterator` internal only. Perhaps should move the file out of `R/` as well so we don't get cran check notes on the call to `rivr`

**Comment by richfitz** [comment]
Good point!  We should decide on if we're tackling streaming at all though (e.g. with jsonlite's streaming functions).

**Comment by sckott** [comment]
I was thinking of streaming in jq dev version https://stedolan.github.io/jq/manual/#Streaming which isn't in 1.4 - which would make sense to include, right?  But yeah, `jsonlite` streaming probably means dropping what we were doing with `rivr` I think

**Comment by richfitz** [comment]
Ah, crap.  That's a bummer.  I think that getting 1.5 to work on windows will be nontrivial, but I can have another look some time.  Though if we come up with a good interface then it won't matter that much.

At the same time, I don't think that streaming is on most people's radar so I'm not sure people will see it as a killer feature.
